### ISSUE TITLE
Typo sourceGUID must be sourcedGUID

### ISSUE THREAD

**Issue by RonaldPannekoek** [omsmith/ims-lti#34]
Hello Owen,

I discoverd a little typo in: 
https://github.com/omsmith/ims-lti/blob/master/src/extensions/outcomes.coffee
Line 42 is now: @body.ele('sourceGUID').ele('sourcedId', source_did)
But has to be: @body.ele('sourcedGUID').ele('sourcedId', source_did)

Now I get a success-message back from http://ltiapps.net/test/tc.php, when I post a outcome.

Thanks for the software,
Ronald Pannekoek

**Comment by omsmith** [comment]
Seems correct. Thanks for reporting the issue @RonaldPannekoek

**Comment by omsmith** [comment]
Released in _2.1.2_
