### ISSUE TITLE
Canvas: Signing fails when a query string is present

### ISSUE THREAD

**Issue by Tape** [omsmith/ims-lti#39]
I'll take a look at this one myself, basically if a query string is present in the request body it is not being correctly accounted for per the OAuth spec. Shouldn't be that difficult of a fix.

**Comment by omsmith** [comment]
Is this not fixed by/related to ba05862f341aefa784a69aa67b6bd131df991628 and #4?

**Comment by Tape** [comment]
I actually have been debugging and this may be a Canvas specific issue, upon inspection I find my query params listed twice. Turns out those query parameters were added to the request body. I'm doing one last test to verify that is the case but I'm actually finding no issues with this extension itself.

**Comment by Tape** [comment]
Just checked the raw request body and it looks like it's including the query params. I'll speak with a Canvas tech and see if there is something we're overlooking. Doesn't appear to be in the spec though.

**Comment by Tape** [comment]
Going to cross reference the ticket: instructure/canvas-lms#600

**Comment by omsmith** [comment]
Great, will let you run with it

**Comment by Tape** [comment]
Going to go ahead and implement this as a "fix" since their choice of implementation is a little off. I'll go ahead and put in some code to special case incoming Canvas requests.

**Comment by Tape** [comment]
Fixed by #41
