### ISSUE TITLE
Clear nonces in MemoryNonceStore

### ISSUE THREAD

**Issue by ttsirkia** [omsmith/ims-lti#40]
Although the module for using Redis exists, in smaller environments `MemoryNonceStore` is enough. However, it leaks memory because the used nonces are never removed.

If the used nonces were saved with the timestamp, checking new nonces could remove the expired nonces with some probability.

**Comment by omsmith** [comment]
Sure thing

**Comment by omsmith** [comment]
Haven't forgotten, just got busy.

I'll get a simpler patch in tonight.

**Comment by ttsirkia** [comment]
No problem. My user count is so small that I'll restart my service anyway before the memory runs out. :-)

**Comment by omsmith** [comment]
Sorry I took so long to get around to it - started right away, but ended up refactored a bunch of things then decided it wasn't worth it really and ended up ignoring it for a while.

I've got #44 open. Clear out old nonces on every read, which isn't wonderful, but if you've a small footprint like you're saying it might be alright.

Let me know what you think.

**Comment by ttsirkia** [comment]
In my opininion, #44 will work fine. If you wanted to increase the performance a bit, I would add a probability of 0.3, for example, to run `clearNonces`.

However, I think this approach is already acceptable because if there is heavy traffic, Redis is of course the suggested way. But if there are only few logins every now and then, it does not matter how efficient the cleaning is because it is more important that some cleaning will happen at some point.
