### ISSUE TITLE
Outcomes extension fails to submit over HTTPS

### ISSUE THREAD

**Issue by ttsirkia** [omsmith/ims-lti#46]
Method `_send_request` seems to be broken if HTTPS is used. It gives the following error message:

```
[Error: Protocol "http:" not supported. Expected "https:".]
```
I'm not sure if the current way of selecting the protocol works as expected. This happens when `lis_outcome_service_url` contains `https`.

**Comment by ttsirkia** [comment]
Just noticed that #45 probably fixes this issue.

**Comment by omsmith** [comment]
Fix by @ktonon available in _v2.1.6_. Apologies for slacking here

**Comment by ttsirkia** [comment]
Thanks! No problem, it was easy to use a local fix before this official one.
